apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "https://+:4443"
  ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PATH: "/dpe-backend/certificates/kestrel/certificate.pfx"
  ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PASSWORD: "DevOpsNaNuvem0!"

  BASEADDRESS__MAIN: "https://ecommerce.devopsproject.com.br/main"
  BASEADDRESS__IDENTITY: "https://ecommerce.devopsproject.com.br/identity"
  BASEADDRESS__ORDER: "https://ecommerce.devopsproject.com.br/order"

  LOCALSTACK__ISENABLED: "false"

  MONGO__DATABASE: "devopsprojectEcommerce"
  MONGO__REPORT_COLLECTION: "reports"
  MONGO_CERTIFICATE_CONTAINER_PATH: "/dpe-backend/certificates/mongo/certificate.pem"

  # Preencher apos: terraform -chdir=devopsproject-ecommerce-iac/terraform/serverless output
  CONNECTIONSTRINGS__DEFAULT: "User ID=devopsprojectAdmin;Password=<SECRETS_MANAGER:rds_master_password>;Host=<TERRAFORM_OUTPUT:rds_proxy_endpoint>;Port=5432;Database=devopsprojectEcommerce;Include Error Detail=true"
  CONNECTIONSTRINGS__MONGO: "mongodb://devopsprojectAdmin:<SECRETS_MANAGER:documentdb_master_password>@<TERRAFORM_OUTPUT:documentdb_cluster_endpoint>:27017/admin?ssl=true&sslInvalidHostNameAllowed=true&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1"

  AWSS3PARAMS01__BUCKETNAME: "devopsproject-application-bucket"
  AWSS3PARAMS01__URIEXPIRATIONMINUTES: "60"

  IDENTITY__ISSUER: "https://ecommerce.devopsproject.com.br/identity"
  IDENTITY__AUDIENCE: "https://ecommerce.devopsproject.com.br"
  IDENTITY__TOKENLIFETIME: "60"
  IDENTITY__KEY: "<YOUR-ENCRYPTED-KEY>"
  IDENTITY__ADMIN__USER: "admin@devopsproject.com.br"
  IDENTITY__ADMIN__USER__PASSWORD: "<YOUR-ENCRYPTED-PASSWORD>"

  HEALTHCHECKSUI__HEALTHCHECKS__0__NAME: "Postgresql"
  HEALTHCHECKSUI__HEALTHCHECKS__0__URI: "https://ecommerce.devopsproject.com.br/healthchecks/health"
  HEALTHCHECKSUI__HEALTHCHECKS__1__NAME: "Main"
  HEALTHCHECKSUI__HEALTHCHECKS__1__URI: "https://ecommerce.devopsproject.com.br/main/health"
  HEALTHCHECKSUI__HEALTHCHECKS__2__NAME: "Order"
  HEALTHCHECKSUI__HEALTHCHECKS__2__URI: "https://ecommerce.devopsproject.com.br/order/health"
  HEALTHCHECKSUI__HEALTHCHECKS__3__NAME: "Notificator"
  HEALTHCHECKSUI__HEALTHCHECKS__3__URI: "https://ecommerce.devopsproject.com.br/notificator/health"
  HEALTHCHECKSUI__HEALTHCHECKS__4__NAME: "Identity Server"
  HEALTHCHECKSUI__HEALTHCHECKS__4__URI: "https://ecommerce.devopsproject.com.br/identity/health"
  HEALTHCHECKSUI__HEALTHCHECKS__5__NAME: "Invoice Generator"
  HEALTHCHECKSUI__HEALTHCHECKS__5__URI: "https://ecommerce.devopsproject.com.br/invoice/health"

  NOTIFICATOR__AWSSQSQUEUEMONITORPARAMS01__QUEUENAME: "EmailNotificationQueue"
  NOTIFICATOR__AWSSQSQUEUEMONITORPARAMS01__QUEUEOWNERAWSACCOUNTID: "794038226274"
  NOTIFICATOR__AWSSQSQUEUEMONITORPARAMS01__MAXNUMBEROFMESSAGES: "10"
  NOTIFICATOR__AWSSQSQUEUEMONITORPARAMS01__WAITTIMESECONDS: "10"
  NOTIFICATOR__AWSSQSQUEUEMONITORPARAMS01__MSGPROCESSORSERVICENAME: "AwsSesEmailSenderProcessor"
  NOTIFICATOR__AWSSQSQUEUEMONITORPARAMS01__MILLISECONDSDELAY: "1000"
  NOTIFICATOR__EMAILCONFIGURATION__FROM: "support@devopsproject.com.br"
  NOTIFICATOR__EMAILCONFIGURATION__TO: "luiz7030@gmail.com"
  NOTIFICATOR__EMAILCONFIGURATION__SESTEMPLATE: "order-confirmed-template"

  MAIN__AWSSQSQUEUEMONITORPARAMS01__QUEUENAME: "ProductStockQueue"
  MAIN__AWSSQSQUEUEMONITORPARAMS01__QUEUEOWNERAWSACCOUNTID: "794038226274"
  MAIN__AWSSQSQUEUEMONITORPARAMS01__MAXNUMBEROFMESSAGES: "10"
  MAIN__AWSSQSQUEUEMONITORPARAMS01__WAITTIMESECONDS: "10"
  MAIN__AWSSQSQUEUEMONITORPARAMS01__MSGPROCESSORSERVICENAME: "ProductStockProcessor"
  MAIN__AWSSQSQUEUEMONITORPARAMS01__MILLISECONDSDELAY: "1000"

  ORDER__AWSSQSMESSAGESENDERPARAMS01__QUEUENAME: "EmailNotificationQueue"
  ORDER__AWSSQSMESSAGESENDERPARAMS01__QUEUEOWNERAWSACCOUNTID: "794038226274"
  ORDER__AWSSQSMESSAGESENDERPARAMS01__ISFIFO: "false"
  ORDER__AWSSQSMESSAGESENDERPARAMS01__ENABLEMESSAGEDEDUPLICATION: "false"
  ORDER__AWSSQSMESSAGESENDERPARAMS02__QUEUENAME: "ProductStockQueue"
  ORDER__AWSSQSMESSAGESENDERPARAMS02__QUEUEOWNERAWSACCOUNTID: "794038226274"
  ORDER__AWSSQSMESSAGESENDERPARAMS02__ISFIFO: "false"
  ORDER__AWSSQSMESSAGESENDERPARAMS02__ENABLEMESSAGEDEDUPLICATION: "false"

  INVOICEGENERATOR__AWSSQSQUEUEMONITORPARAMS01__QUEUENAME: "InvoiceQueue"
  INVOICEGENERATOR__AWSSQSQUEUEMONITORPARAMS01__QUEUEOWNERAWSACCOUNTID: "794038226274"
  INVOICEGENERATOR__AWSSQSQUEUEMONITORPARAMS01__MAXNUMBEROFMESSAGES: "10"
  INVOICEGENERATOR__AWSSQSQUEUEMONITORPARAMS01__WAITTIMESECONDS: "10"
  INVOICEGENERATOR__AWSSQSQUEUEMONITORPARAMS01__MSGPROCESSORSERVICENAME: "InvoiceProcessor"
  INVOICEGENERATOR__AWSSQSQUEUEMONITORPARAMS01__MILLISECONDSDELAY: "1000"
  INVOICEGENERATOR__AWSSQSMESSAGESENDERPARAMS01__QUEUENAME: "EmailNotificationQueue"
  INVOICEGENERATOR__AWSSQSMESSAGESENDERPARAMS01__QUEUEOWNERAWSACCOUNTID: "794038226274"
  INVOICEGENERATOR__AWSSQSMESSAGESENDERPARAMS01__ISFIFO: "false"
  INVOICEGENERATOR__AWSSQSMESSAGESENDERPARAMS01__ENABLEMESSAGEDEDUPLICATION: "false"
